name: publish

env:
  CI: true

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: prepare
        run: cp -r ./@types ./dist/@types && cp package.json index.d.ts README.md LICENSE CHANGELOG.md CONTRIBUTING.md CODE_OF_CONDUCT.md ./dist

      - name: publish
        run: |
          npm pack
          npm publish --access public
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
