name: publish

env:
  CI: true
  NODE_ENV: production

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: tests
        run: npm test -- --coverage

      - name: build-doc
        run: npm run build-doc --if-present

      - name: prepare
        run: cp -r ./@types ./dist/@types && cp package.json index.d.ts README.md LICENSE CHANGELOG.md CONTRIBUTING.md CODE_OF_CONDUCT.md ./dist

      - name: publish
        run: |
          npm pack
          npm publish --tag next
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
